// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcuqc-LwaQFPej9jiIBqiqVB2DAwrVy3Q',
    appId: '1:868810906217:web:cf50c434d816e6cfd160f8',
    messagingSenderId: '868810906217',
    projectId: 'dompetku-88476',
    authDomain: 'dompetku-88476.firebaseapp.com',
    storageBucket: 'dompetku-88476.firebasestorage.app',
    measurementId: 'G-KC0MZ3BZ5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDswhM3OPbcRPO5HwK-dx5bGIE84qQbSaE',
    appId: '1:868810906217:android:f05bb705b1052195d160f8',
    messagingSenderId: '868810906217',
    projectId: 'dompetku-88476',
    storageBucket: 'dompetku-88476.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJVbf__2UjQ9DIMTlGM-9N4UFX-fGbBn4',
    appId: '1:868810906217:ios:ad0e455aa0fe5c93d160f8',
    messagingSenderId: '868810906217',
    projectId: 'dompetku-88476',
    storageBucket: 'dompetku-88476.firebasestorage.app',
    iosBundleId: 'com.example.dompetku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJVbf__2UjQ9DIMTlGM-9N4UFX-fGbBn4',
    appId: '1:868810906217:ios:ad0e455aa0fe5c93d160f8',
    messagingSenderId: '868810906217',
    projectId: 'dompetku-88476',
    storageBucket: 'dompetku-88476.firebasestorage.app',
    iosBundleId: 'com.example.dompetku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcuqc-LwaQFPej9jiIBqiqVB2DAwrVy3Q',
    appId: '1:868810906217:web:df24e41c6a77524bd160f8',
    messagingSenderId: '868810906217',
    projectId: 'dompetku-88476',
    authDomain: 'dompetku-88476.firebaseapp.com',
    storageBucket: 'dompetku-88476.firebasestorage.app',
    measurementId: 'G-56L78F9BF2',
  );

}